name: k8s build images ci

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: gcr->dockerhub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
        working-directory: scripts
        run: chmod +x k8s-build-images-get.sh && ./k8s-build-images-get.sh
